# Generated by Django 4.0.2 on 2022-04-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=128)),
                ('avatar', models.CharField(max_length=128)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=128)),
                ('mfa_enabled', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
