# Generated by Django 4.0.2 on 2022-02-18 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.game'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
