# Generated by Django 4.0.2 on 2022-04-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_team_game_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrim',
            name='responses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
